Fix issues with loading JSON and add basic documentation.
KabirKwatra/AnimeKiller pull request #2
Opened 2020-04-15 16:07 UTC by DiegoMagdaleno

- Fixes an issue with loading the JSON file, the code is replaced by `json.load` instead of `json.loads`.

- Adds basic tutorial on how to run the bot.

2020-04-16 07:06 UTC, KabirKwatra commented
So here is the thing: I have this bot hosted on Heroku, so I am actually storing the contents of the JSON file in the environment variable. When`json.loads` is used, we are parsing the variable, not the file that it points to.

I do appreciate the documentation.

2020-04-16 07:13 UTC, Kab1r requested changes

2020-04-16 07:13 UTC, KabirKwatra commented on run_bot.py
> -        json.loads(
Revert to loads?

2020-04-17 15:45 UTC, DiegoMagdaleno commented
Now it will detect if its a file and use load if not if it will use loads, that way nothing should break and allows people to export their env variable as whatever they consider better.

2020-04-17 19:31 UTC, Kab1r approved these changes

2020-04-17 19:36 UTC, KabirKwatra commented
Merged in #3

2020-04-17 19:36 UTC, closed without merging